_BASE_: "Base-PoseNet-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    # Since batch size per GPU is 8
    PRE_NMS_TOPK_TRAIN: 8000  # Per FPN level, old: 2000
    PRE_NMS_TOPK_TEST: 4000  # Per FPN level, old: 1000
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    # 1000 proposals per-image is found to hurt box AP.
    # Therefore we increase it to 1500 per-image.
    POST_NMS_TOPK_TRAIN: 8000
    POST_NMS_TOPK_TEST: 4000
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  RPN:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
  ROI_HEADS:
    NAME: "FasterRCNNROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_KEYPOINT_HEAD:
    NAME: "PoseConvHead"
    POOLER_RESOLUTION: 7
    CONV_DIMS: (256, 256, 256, 256, 256, 256, 256, 256)
    LOSS_WEIGHT: 1.0
SOLVER:
  BASE_LR: 0.005
