_BASE_: "Base-PoseNet-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  RPN:
    BATCH_SIZE_PER_IMAGE: 64
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_KEYPOINT_HEAD:
    NAME: "KRCNNConvDeconvUpsampleHead"
    CONV_DIMS: [128, 128, 128, 128]
DATASETS:
  TRAIN: ("keypoints_coco_2017_val_100",)
  TEST: ("keypoints_coco_2017_val_100",)
SOLVER:
  BASE_LR: 0.005
  STEPS: (30,)
  MAX_ITER: 40
  IMS_PER_BATCH: 2
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 10
DATALOADER:
  NUM_WORKERS: 2
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 128
  MIN_SIZE_TRAIN: (128,)
