_BASE_: "kprcnn_R_50_FPN_1x.yaml"
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PROPOSAL_FILES_TEST: ()
  TEST: ('coco_2017_testdev',)
TEST:
  AUG:
    ENABLED: False
    FLIP: True
    MAX_SIZE: 4000
    MIN_SIZES: (800,)
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 0
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 200
