MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  KEYPOINT_ON: True
  WEIGHTS: "./posenet/backbone/models/mobilenetv3_100-35495452.pth"
  BACKBONE:
    NAME: "build_mb3_fpn_backbone"
  MOBILENETV3:
    OUT_FEATURES: ["res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 256
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  RPN:
    HEAD_NAME: "LiteRPNHeadDW"
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    # 1000 proposals per-image is found to hurt box AP.
    # Therefore we increase it to 1500 per-image.
    POST_NMS_TOPK_TRAIN: 1500
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "LiteFastRCNNConvFCHead"
    # NAME: "FastRCNNConvFCHead"
    NORM: "GN"
    NUM_CONV: 0
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    CONV_DIM: 256
    FC_DIM: 1024
  ROI_KEYPOINT_HEAD:
    # NAME: "KRCNNConvDeconvUpsampleHead"
    NAME: "LitePoseDWConvDeconvUpsampleHead"
    NORM: "GN"
    CONV_DIMS: [512, 512, 512, 512, 512, 512, 512, 512]
DATASETS:
  TRAIN: ("keypoints_coco_2017_train",)
  TEST: ("keypoints_coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  GRAD_CLIP: 10
INPUT:
  CROP:
    ENABLED: True
    SIZE: [0.9, 0.9]
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 320
  MIN_SIZE_TRAIN: (256, 320, 384)
