_BASE_: "litepose_MB3_FPN_1x.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 3
  RPN:
    BATCH_SIZE_PER_IMAGE: 64
  ROI_KEYPOINT_HEAD:
    CONV_DIMS: [64, 64, 64]
DATASETS:
  TRAIN: ("keypoints_coco_2017_val_100",)
  TEST: ("keypoints_coco_2017_val_100",)
SOLVER:
  BASE_LR: 0.02
  STEPS: (6000, 8000,)
  MAX_ITER: 9000
  IMS_PER_BATCH: 16
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
DATALOADER:
  NUM_WORKERS: 2
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 128
  MIN_SIZE_TRAIN: (128,)
